# Generated by Django 4.2.2 on 2023-06-16 10:23

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Bolümiň ady')),
            ],
            options={
                'verbose_name': 'Bolümiň ady',
                'verbose_name_plural': 'Bolümiň atlary',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Ýerleşýän ýeri(Şäher, etrap)')),
            ],
            options={
                'verbose_name': 'Ýerleşýän ýeri(Şäher, etrap)',
                'verbose_name_plural': 'Ýerleşýän ýerleri(Şäher, etrap)',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Wezipesi')),
            ],
            options={
                'verbose_name': 'Wezipesi',
                'verbose_name_plural': 'Wezipeleri',
            },
        ),
        migrations.CreateModel(
            name='PlaceOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Edaranyň ady')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='phone_book.placeofwork')),
            ],
            options={
                'verbose_name': 'Edaranyň ady',
                'verbose_name_plural': 'Edaranyň atlary',
            },
        ),
        migrations.CreateModel(
            name='PhoneBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Ady')),
                ('last_name', models.CharField(max_length=50, verbose_name='Familiyasy')),
                ('mobile_phone', models.CharField(max_length=50, verbose_name='El telefony')),
                ('work_phone', models.CharField(max_length=50, verbose_name='Is telefony')),
                ('home_address', models.CharField(max_length=250, verbose_name='Öý salgysy')),
                ('birthday', models.DateField(verbose_name='Doglan guni')),
                ('department_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_name', to='phone_book.departmentname', verbose_name='Bölümiň ady')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location', to='phone_book.location', verbose_name='Ýerleşýän ýeri(Şäher, etrap)')),
                ('place_of_work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_of_work', to='phone_book.placeofwork', verbose_name='Isleyan yeri')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position', to='phone_book.position', verbose_name='Wezipesi')),
            ],
        ),
    ]
